# Do not modify this file! (unless you know what you are doing!)
# It was generated by ‘nixos-generate-config’ and may be
# overwritten by future invocations. Please make changes to
# /etc/nixos/configuration.nix instead.
# hardware: qnap
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/529fb37d-ba9a-4367-bfab-b5800e6b9325";
    fsType = "ext4";
  };

  # NOTE: Uncomment this to allow for automounting
  # fileSystems."/mnt/nas/media" = {
  #   device = "nas/media";
  #   fsType = "zfs";
  #   options = [ "zfsutil" ];
  # };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d00836c2-3443-4e86-b327-f6d76a483461";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp111s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp115s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp116s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
