#!/usr/bin/env zsh

# simple utility to show all directories/files under directory.
# defaults to using the parent git directory of currently focused window

# configure logger
LOGGER=$(which logger)
logger() {
    $LOGGER --tag fzf-filesystem-open -- "$@"
}

MODE=$1           # accepted values: -f / -d
GLOBAL_SEARCH=$2  # accepted values: -g / null

if [ "$MODE" = "-f" ]; then
    prompt_noun="file"
    find_type="f"
elif [ "$MODE" = "-d" ]; then
    prompt_noun="directory"
    find_type="d"
else
    logger "unknown mode $MODE"
    return
fi

# get the last focused wid generated by the save-window-id.sh script
source "/tmp/.wid/$(cat /tmp/.last_focused_wid)" > /dev/null 2>&1

if [ "$GLOBAL_SEARCH" = "-g" ]; then
    logger "global mode, using ${HOME}"
    FILESYSTEM_POINTER=$HOME
elif [ -z "${WINDOW_PWD}" ]; then
    logger "no previous window, using ${HOME}"
    FILESYSTEM_POINTER=$HOME
else
    logger "loaded from old window: ${WINDOW_PWD}"
    if ! FILESYSTEM_POINTER=$(git -C "${WINDOW_PWD}" rev-parse --show-toplevel); then
        logger "unable to find parent git repo"
        FILESYSTEM_POINTER=$HOME
    fi
fi

selection=$(find "$FILESYSTEM_POINTER" -not -path '*/.*' -type "$find_type" \
    | sed -e "s|^$FILESYSTEM_POINTER|\.|g" \
    | fzf -m --ansi --reverse \
        --prompt="Open $prompt_noun: " \
        --header="(Currently in $FILESYSTEM_POINTER)" \
        --preview="$HOME/.config/sxhkd/fzf-file-preview.sh $FILESYSTEM_POINTER/{}")

if [ -z "$selection" ]; then
    return
fi

echo "$selection" | while read -r selected_item; do
    item_full_path="$FILESYSTEM_POINTER/$selected_item"
    if [ -f "$item_full_path" ]; then
        nohup alacritty \
            --working-directory $(dirname "$item_full_path") \
            --command zsh -c "$EDITOR $item_full_path" \
            > /dev/null 2>&1 &
    elif [ -d "$item_full_path" ]; then
        nohup alacritty \
            --working-directory "$item_full_path" \
            > /dev/null 2>&1 &
    else
        logger "ERROR: unknown type, skipping $selected_item"
    fi
done
sleep 0.1
return
