#!/usr/bin/env zsh

# simple utility to show all directories under directory.
# defaults to using the directory of currently focused window

# FIXME: commonize with the file open script

# configure logger
LOGGER=$(which logger)
logger() {$LOGGER --tag fzf-directory-open -- $@}

# get the last focused wid generated by the save-window-id.sh script
source /tmp/.wid/$(cat /tmp/.last_focused_wid) > /dev/null 2>&1
if [ -z "${WINDOW_PWD}" ]; then
    logger "no previous window, using ${HOME}"
    FILESYSTEM_POINTER=$HOME
else
    logger "loaded from old window: ${WINDOW_PWD}"
    FILESYSTEM_POINTER=$(git -C ${WINDOW_PWD} rev-parse --show-toplevel)
    if [ $? -ne 0 ]; then
        logger "unable to find parent git repo"
        FILESYSTEM_POINTER=$HOME
    fi
fi

selection=$(find $FILESYSTEM_POINTER -not -path '*/.*' -type d \
    | sed -e "s|^$FILESYSTEM_POINTER|\.|g" \
    | fzf -m --ansi --reverse \
        --prompt="Open directory: " \
        --header="(Currently in $FILESYSTEM_POINTER)" \
        --preview="$HOME/.config/sxhkd/fzf-file-preview.sh $FILESYSTEM_POINTER/{}")

if [ -z "$selection" ]; then
    return
fi

echo $selection | while read -r selected_directory; do
    nohup alacritty \
        --working-directory $FILESYSTEM_POINTER/$selected_directory > /dev/null 2>&1 &
done
sleep 0.1
return
