#!/usr/bin/env zsh

# simple utility to show all files under directory.
# defaults to using the directory of currently focused window

# configure logger
LOGGER=$(which logger)
logger() {$LOGGER --tag fzf-file-open -- $@}

# get the last focused wid generated by the save-window-id.sh script
source /tmp/.wid/$(cat /tmp/.last_focused_wid) > /dev/null 2>&1
if [ -z "${WINDOW_PWD}" ]; then
    logger "no previous window, using ${HOME}"
    FILESYSTEM_POINTER=$HOME
else
    logger "loaded from old window: ${WINDOW_PWD}"
    FILESYSTEM_POINTER=${WINDOW_PWD}
fi

selection=$(find $FILESYSTEM_POINTER -not -path '*/.*' -type f | \
    fzf -m --ansi --reverse \
        --preview $HOME'/.config/sxhkd/fzf-file-preview.sh {}')

if [ -z "$selection" ]; then
    return
fi

echo $selection | while read -r selected_file; do
    nohup alacritty \
        --working-directory $(dirname $selected_file) \
        --command zsh -c "$EDITOR $selected_file" > /dev/null 2>&1 &
done
sleep 0.1
return
